"""add api_clients table

Revision ID: f016d69ce600
Revises: b31722549850
Create Date: 2026-08-03 10:59:37.077604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f016d69ce600'
down_revision: Union[str, None] = 'b31722549850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('hashed_client_secret', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_clients_client_id'), 'api_clients', ['client_id'], unique=True)
    op.create_index(op.f('ix_api_clients_id'), 'api_clients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_clients_id'), table_name='api_clients')
    op.drop_index(op.f('ix_api_clients_client_id'), table_name='api_clients')
    op.drop_table('api_clients')
    # ### end Alembic commands ###
